/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.mycompany.type.writer;

/**
 *
 * @author ubuntu
 */
public class twstrings {
    
    String words[] = {
    "piano", "zebra", "frog", "juice", "cat", "lemon", "apple", "monkey", "yellow", "keyboard",
    "quilt", "ball", "giraffe", "snake", "carrot", "house", "orange", "bird", "elephant",
    "watermelon", "banana", "tiger", "peanut", "chair", "grape", "octopus", "flower", "dog",
    "lion", "pear", "jacket", "umbrella", "rabbit", "blueberry", "hat", "dolphin", "koala",
    "ice cream", "pencil", "kiwi", "whale", "table", "zeppelin", "violet", "necklace", "cheese",
    "kangaroo", "boat", "grapefruit", "book", "cake", "penguin", "strawberry", "shirt",
    "elephant", "cookie", "shark", "plane", "butterfly", "guitar", "pineapple", "turtle",
    "sunflower", "lamp", "zebra", "drum", "cupcake", "zeppelin", "carrot", "bag", "leopard",
    "lemon", "robot", "watermelon", "sun", "ice cream", "orange", "fox", "pencil", "butterfly",
    "moon", "ball", "cat", "banana", "bat", "umbrella", "jellyfish", "orange", "snowman", "book",
    "butterfly", "dog", "lemon", "piano", "camera", "elephant", "cactus", "koala", "duck", "juice",
    "bear", "zeppelin", "car", "quilt", "grape", "jacket", "giraffe", "rainbow", "kiwi", "house",
    "jacket", "ball", "apple", "pig", "cow", "piano", "watermelon", "orange", "sunflower", "moon",
    "cup", "cat", "umbrella", "zebra", "snake", "hat", "table", "pineapple", "ball", "zeppelin",
    "monkey", "pencil", "duck", "carrot", "penguin", "sun", "lemon", "bird", "zebra", "butterfly",
    "koala", "flower", "cake", "whale", "juice", "octopus", "jacket", "dolphin", "leopard",
    "robot", "book", "elephant", "lion", "cheese", "apple", "chair", "dog", "grapefruit",
    "boat", "snake", "banana", "ice cream", "cat", "piano", "zeppelin", "orange", "pineapple",
    "umbrella", "guitar", "watermelon", "sunflower", "penguin", "lemon", "butterfly", "hat",
    "dolphin", "zebra", "ball", "book", "cow", "elephant", "carrot", "octopus", "grape",
    "house", "jacket", "kiwi", "leopard", "pig", "snake", "banana", "blueberry", "cup",
    "zeppelin", "tiger", "butterfly", "cat", "lemon", "piano", "kiwi", "duck", "ball",
    "umbrella", "orange", "dog", "zebra", "moon", "elephant", "cactus", "juice", "snake",
    "bear", "zeppelin", "car", "quilt", "giraffe", "kiwi", "jacket", "dolphin", "house",
    "penguin", "leopard", "robot", "book", "cheese", "lion", "apple", "chair", "cat",
    "dog", "snake", "banana", "zeppelin", "orange", "watermelon", "butterfly", "piano",
    "lemon", "pig", "elephant", "jacket", "hat", "koala", "moon", "ball", "octopus",
    "bird", "umbrella", "cow", "zebra", "carrot", "dog", "grape", "blueberry", "kiwi",
    "house", "penguin", "leopard", "snake", "book", "cheese", "cat", "banana", "zeppelin",
    "orange", "sunflower", "elephant", "butterfly", "lemon", "piano", "hat", "duck", "ball",
    "umbrella", "moon", "dog", "zebra", "snake", "kiwi", "octopus", "house", "penguin",
    "apple", "robot", "lion", "book", "cheese", "jacket", "car", "banana", "cat",
    "lemon", "zeppelin", "orange", "butterfly", "piano", "duck", "ball", "umbrella", "dog",
    "moon", "zebra", "snake", "elephant", "koala", "hat", "cow", "penguin", "octopus",
    "leopard", "book", "jacket", "cheese", "car", "banana", "cat", "lemon", "zeppelin",
    "orange", "butterfly", "piano", "duck", "ball", "umbrella", "dog", "moon", "zebra",
    "snake", "elephant", "koala", "hat", "cow", "penguin", "octopus", "leopard", "book",
    "jacket", "cheese", "car", "banana", "cat", "lemon", "zeppelin", "orange", "butterfly",
    "piano", "duck", "ball", "umbrella", "dog", "moon", "zebra", "snake", "elephant",
    "koala", "hat", "cow", "penguin", "octopus", "leopard", "book", "jacket", "cheese",
    "car", "banana", "cat", "lemon", "zeppelin", "orange", "butterfly", "piano", "duck",
    "ball", "umbrella", "dog", "moon", "zebra", "snake", "elephant", "koala", "hat",
    "cow", "penguin", "octopus", "leopard", "book", "jacket", "cheese", "car", "banana",
    "cat", "lemon", "zeppelin", "orange", "butterfly", "piano", "duck", "ball", "umbrella",
    "dog", "moon", "zebra", "snake", "elephant", "koala", "hat", "cow", "penguin",
    "octopus", "leopard", "book", "jacket", "cheese", "car", "banana", "cat", "lemon",
    "zeppelin", "orange", "butterfly", "piano", "duck", "ball", "umbrella", "dog", "moon",
    "zebra", "snake", "elephant", "koala", "hat", "cow", "penguin", "octopus", "leopard",
    "book", "jacket", "cheese", "car", "banana", "cat", "lemon", "zeppelin", "orange",
    "butterfly", "piano", "duck", "ball", "umbrella", "dog", "moon", "zebra", "snake",
    "elephant", "koala", "hat", "cow", "penguin", "octopus", "leopard", "book", "jacket",
    "cheese", "car", "banana", "cat", "lemon", "zeppelin", "orange", "butterfly", "piano",
    "duck", "ball", "umbrella", "dog", "moon", "zebra", "snake", "elephant", "koala",
    "hat", "cow", "penguin", "octopus", "leopard", "book", "jacket", "cheese", "car",
    "banana", "cat", "lemon", "zeppelin", "orange", "butterfly", "piano", "duck", "ball",
    "umbrella", "dog", "moon", "zebra", "snake", "elephant", "koala", "hat", "cow",
    "penguin", "octopus", "leopard", "book", "jacket", "cheese", "car", "banana", "cat",
    "lemon", "zeppelin", "orange", "butterfly", "piano", "duck", "ball", "umbrella", "dog",
    "moon", "zebra", "snake", "elephant", "koala", "hat", "cow", "penguin", "octopus",
    "leopard", "book", "jacket", "cheese", "car", "banana", "cat", "lemon", "zeppelin",
    "orange", "butterfly", "piano", "duck", "ball", "umbrella", "dog", "moon", "zebra",
    "snake", "elephant", "koala", "hat", "cow", "penguin", "octopus", "leopard", "book",
    "jacket", "cheese", "car", "banana", "cat", "lemon", "zeppelin", "orange", "butterfly",
    "piano", "duck", "ball", "umbrella", "dog", "moon", "zebra", "snake", "elephant",
    "koala", "hat", "cow", "penguin", "octopus", "leopard", "book", "jacket", "cheese",
    "car", "banana", "cat", "lemon", "zeppelin", "orange", "butterfly", "piano", "duck",
    "ball", "umbrella", "dog", "moon", "zebra", "snake", "elephant", "koala", "hat",
    "cow", "penguin", "octopus", "leopard", "book", "jacket", "cheese", "car", "banana",
    "cat", "lemon", "zeppelin", "orange", "butterfly", "piano", "duck", "ball", "umbrella",
    "dog", "moon", "zebra", "snake", "elephant", "koala", "hat", "cow", "penguin",
    "octopus", "leopard", "book", "jacket", "cheese", "car", "banana", "cat", "lemon",
    "zeppelin", "orange", "butterfly", "piano", "duck", "ball", "umbrella", "dog", "moon",
    "zebra", "snake", "elephant", "koala", "hat", "cow", "penguin", "octopus", "leopard",
    "book", "jacket", "cheese", "car", "banana", "cat",    "piano", "zebra", "frog", "juice",
        "piano", "zebra", "frog", "juice", "cat", "lemon", "apple", "monkey", "yellow", "keyboard",
    "quilt", "ball", "giraffe", "snake", "carrot", "house", "orange", "bird", "elephant",
    "watermelon", "banana", "tiger", "peanut", "chair", "grape", "octopus", "flower", "dog",
    "lion", "pear", "jacket", "umbrella", "rabbit", "blueberry", "hat", "dolphin", "koala",
    "ice cream", "pencil", "kiwi", "whale", "table", "zeppelin", "violet", "necklace", "cheese",
    "kangaroo", "boat", "grapefruit", "book", "cake", "penguin", "strawberry", "shirt",
    "elephant", "cookie", "shark", "plane", "butterfly", "guitar", "pineapple", "turtle",
    "sunflower", "lamp", "zebra", "drum", "cupcake", "zeppelin", "carrot", "bag", "leopard",
    "lemon", "robot", "watermelon", "sun", "ice cream", "orange", "fox", "pencil", "butterfly",
    "moon", "ball", "cat", "banana", "bat", "umbrella", "jellyfish", "orange", "snowman", "book",
    "butterfly", "dog", "lemon", "piano", "camera", "elephant", "cactus", "koala", "duck", "juice",
    "bear", "zeppelin", "car", "quilt", "grape", "jacket", "giraffe", "rainbow", "kiwi", "house",
    "jacket", "ball", "apple", "pig", "cow", "piano", "watermelon", "orange", "sunflower", "moon",
    "cup", "cat", "umbrella", "zebra", "snake", "hat", "table", "pineapple", "ball", "zeppelin",
    "monkey", "pencil", "duck", "carrot", "penguin", "sun", "lemon", "bird", "zebra", "butterfly",
    "koala", "flower", "cake", "whale", "juice", "octopus", "jacket", "dolphin", "leopard",
    "robot", "book", "elephant", "lion", "cheese", "apple", "chair", "dog", "grapefruit",
    "boat", "snake", "banana", "ice cream", "cat", "piano", "zeppelin", "orange", "pineapple",
    "umbrella", "guitar", "watermelon", "sunflower", "penguin", "lemon", "butterfly", "hat",
    "dolphin", "zebra", "ball", "book", "cow", "elephant", "carrot", "octopus", "grape",
    "house", "jacket", "kiwi", "leopard", "pig", "snake", "banana", "blueberry", "cup",
    "zeppelin", "tiger", "butterfly", "cat", "lemon", "piano", "kiwi", "duck", "ball",
    "umbrella", "orange", "dog", "zebra", "moon", "elephant", "cactus", "juice", "snake",
    "bear", "zeppelin", "car", "quilt", "giraffe", "kiwi", "jacket", "dolphin", "house",
    "penguin", "leopard", "robot", "book", "cheese", "lion", "apple", "chair", "cat",
    "dog", "snake", "banana", "zeppelin", "orange", "watermelon", "butterfly", "piano",
    "lemon", "pig", "elephant", "jacket", "hat", "koala", "moon", "ball", "octopus",
    "bird", "umbrella", "cow", "zebra", "carrot", "dog", "grape", "blueberry", "kiwi",
    "house", "penguin", "leopard", "snake", "book", "cheese", "cat", "banana", "zeppelin",
    "orange", "sunflower", "elephant", "butterfly", "lemon", "piano", "hat", "duck", "ball",
    "umbrella", "moon", "dog", "zebra", "snake", "kiwi", "octopus", "house", "penguin",
    "apple", "robot", "lion", "book", "cheese", "jacket", "car", "banana", "cat",
    "lemon", "zeppelin", "orange", "butterfly", "piano", "duck", "ball", "umbrella", "dog",
    "moon", "zebra", "snake", "elephant", "koala", "hat", "cow", "penguin", "octopus",
    "leopard", "book", "jacket", "cheese", "car", "banana", "cat", "lemon", "zeppelin",
    "orange", "butterfly", "piano", "duck", "ball", "umbrella", "dog", "moon", "zebra",
    "snake", "elephant", "koala", "hat", "cow", "penguin", "octopus", "leopard", "book",
    "jacket", "cheese", "car", "banana", "cat", "lemon", "zeppelin", "orange", "butterfly",
    "piano", "duck", "ball", "umbrella", "dog", "moon", "zebra", "snake", "elephant",
    "koala", "hat", "cow", "penguin", "octopus", "leopard", "book", "jacket", "cheese",
    "car", "banana", "cat", "lemon", "zeppelin", "orange", "butterfly", "piano", "duck",
    "ball", "umbrella", "dog", "moon", "zebra", "snake", "elephant", "koala", "hat",
    "cow", "penguin", "octopus", "leopard", "book", "jacket", "cheese", "car", "banana",
    "cat", "lemon", "zeppelin", "orange", "butterfly", "piano", "duck", "ball", "umbrella",
    "dog", "moon", "zebra", "snake", "elephant", "koala", "hat", "cow", "penguin",
    "octopus", "leopard", "book", "jacket", "cheese", "car", "banana", "cat", "lemon",
    "zeppelin", "orange", "butterfly", "piano", "duck", "ball", "umbrella", "dog", "moon",
    "zebra", "snake", "elephant", "koala", "hat", "cow", "penguin", "octopus", "leopard",
    "book", "jacket", "cheese", "car", "banana", "cat", "lemon", "zeppelin", "orange",
    "butterfly", "piano", "duck", "ball", "umbrella", "dog", "moon", "zebra", "snake",
    "elephant", "koala", "hat", "cow", "penguin", "octopus", "leopard", "book", "jacket",
    "cheese", "car", "banana", "cat", "lemon", "zeppelin", "orange", "butterfly", "piano",
    "duck", "ball", "umbrella", "dog", "moon", "zebra", "snake", "elephant", "koala",
    "hat", "cow", "penguin", "octopus", "leopard", "book", "jacket", "cheese", "car",
    "banana", "cat", "lemon", "zeppelin", "orange", "butterfly", "piano", "duck", "ball",
    "umbrella", "dog", "moon", "zebra", "snake", "elephant", "koala", "hat", "cow",
    "penguin", "octopus", "leopard", "book", "jacket", "cheese", "car", "banana", "cat",
    "lemon", "zeppelin", "orange", "butterfly", "piano", "duck", "ball", "umbrella", "dog",
    "moon", "zebra", "snake", "elephant", "koala", "hat", "cow", "penguin", "octopus",
    "leopard", "book", "jacket", "cheese", "car", "banana", "cat", "lemon", "zeppelin",
    "orange", "butterfly", "piano", "duck", "ball", "umbrella", "dog", "moon", "zebra",
    "snake", "elephant", "koala", "hat", "cow", "penguin", "octopus", "leopard", "book",
    "jacket", "cheese", "car", "banana", "cat", "lemon", "zeppelin", "orange", "butterfly",
    "piano", "duck", "ball", "umbrella", "dog", "moon", "zebra", "snake", "elephant",
    "koala", "hat", "cow", "penguin", "octopus", "leopard", "book", "jacket", "cheese",
    "car", "banana", "cat", "lemon", "zeppelin", "orange", "butterfly", "piano", "duck",
    "ball", "umbrella", "dog", "moon", "zebra", "snake", "elephant", "koala", "hat",
    "cow", "penguin", "octopus", "leopard", "book", "jacket", "cheese", "car", "banana",
    "cat", "lemon", "zeppelin", "orange", "butterfly", "piano", "duck", "ball", "umbrella",
    "dog", "moon", "zebra", "snake", "elephant", "koala", "hat", "cow", "penguin",
    "octopus", "leopard", "book", "jacket", "cheese", "car", "banana", "cat", "lemon",
    "zeppelin", "orange", "butterfly", "piano", "duck", "ball", "umbrella", "dog", "moon",
    "zebra", "snake", "elephant", "koala", "hat", "cow", "penguin", "octopus", "leopard",
    "book", "jacket", "cheese", "car", "banana","cat", "lemon", "apple", "monkey", "yellow", "keyboard",
    "quilt", "ball", "giraffe", "snake", "carrot", "house", "orange", "bird", "elephant",
    "watermelon", "banana", "tiger", "peanut", "chair", "grape", "octopus", "flower", "dog",
    "lion", "pear", "jacket", "umbrella", "rabbit", "blueberry", "hat", "dolphin", "koala",
    "ice cream", "pencil", "kiwi", "whale", "table", "zeppelin", "violet", "necklace", "cheese",
    "kangaroo", "boat", "grapefruit", "book", "cake", "penguin", "strawberry", "shirt",
    "elephant", "cookie", "shark", "plane", "butterfly", "guitar", "pineapple", "turtle",
    "sunflower", "lamp", "zebra", "drum", "cupcake", "zeppelin", "carrot", "bag", "leopard",
    "lemon", "robot", "watermelon", "sun", "ice cream", "orange", "fox", "pencil", "butterfly",
    "moon", "ball", "cat", "banana", "bat", "umbrella", "jellyfish", "orange", "snowman", "book",
    "butterfly", "dog", "lemon", "piano", "camera", "elephant", "cactus", "koala", "duck", "juice",
    "bear", "zeppelin", "car", "quilt", "grape", "jacket", "giraffe", "rainbow", "kiwi", "house",
    "jacket", "ball", "apple", "pig", "cow", "piano", "watermelon", "orange", "sunflower", "moon",
    "cup", "cat", "umbrella", "zebra", "snake", "hat", "table", "pineapple", "ball", "zeppelin",
    "monkey", "pencil", "duck", "carrot", "penguin", "sun", "lemon", "bird", "zebra", "butterfly",
    "koala", "flower", "cake", "whale", "juice", "octopus", "jacket", "dolphin", "leopard",
    "robot", "book", "elephant", "lion", "cheese", "apple", "chair", "dog", "grapefruit",
    "boat", "snake", "banana", "ice cream", "cat", "piano", "zeppelin", "orange", "pineapple",
    "umbrella", "guitar", "watermelon", "sunflower", "penguin", "lemon", "butterfly", "hat",
    "dolphin", "zebra", "ball", "book", "cow", "elephant", "carrot", "octopus", "grape",
    "house", "jacket", "kiwi", "leopard", "pig", "snake", "banana", "blueberry", "cup",
    "zeppelin", "tiger", "butterfly", "cat", "lemon", "piano", "kiwi", "duck", "ball",
    "umbrella", "orange", "dog", "zebra", "moon", "elephant", "cactus", "juice", "snake",
    "bear", "zeppelin", "car", "quilt", "giraffe", "kiwi", "jacket", "dolphin", "house",
    "penguin", "leopard", "robot", "book", "cheese", "lion", "apple", "chair", "cat",
    "dog", "snake", "banana", "zeppelin", "orange", "watermelon", "butterfly", "piano",
    "lemon", "pig", "elephant", "jacket", "hat", "koala", "moon", "ball", "octopus",
    "bird", "umbrella", "cow", "zebra", "carrot", "dog", "grape", "blueberry", "kiwi",
    "house", "penguin", "leopard", "snake", "book", "cheese", "cat", "banana", "zeppelin",
    "orange", "sunflower", "elephant", "butterfly", "lemon", "piano", "hat", "duck", "ball",
    "umbrella", "moon", "dog", "zebra", "snake", "kiwi", "octopus", "house", "penguin",
    "apple", "robot", "lion", "book", "cheese", "jacket", "car", "banana", "cat",
    "lemon", "zeppelin", "orange", "butterfly", "piano", "duck", "ball", "umbrella", "dog",
    "moon", "zebra", "snake", "elephant", "koala", "hat", "cow", "penguin", "octopus",
    "leopard", "book", "jacket", "cheese", "car", "banana", "cat", "lemon", "zeppelin",
    "orange", "butterfly", "piano", "duck", "ball", "umbrella", "dog", "moon", "zebra",
    "snake", "elephant", "koala", "hat", "cow", "penguin", "octopus", "leopard", "book",
    "jacket", "cheese", "car", "banana", "cat", "lemon", "zeppelin", "orange", "butterfly",
    "piano", "duck", "ball", "umbrella", "dog", "moon", "zebra", "snake", "elephant",
    "koala", "hat", "cow", "penguin", "octopus", "leopard", "book", "jacket", "cheese",
    "car", "banana", "cat", "lemon", "zeppelin", "orange", "butterfly", "piano", "duck",
    "ball", "umbrella", "dog", "moon", "zebra", "snake", "elephant", "koala", "hat",
    "cow", "penguin", "octopus", "leopard", "book", "jacket", "cheese", "car", "banana",
    "cat", "lemon", "zeppelin", "orange", "butterfly", "piano", "duck", "ball", "umbrella",
    "dog", "moon", "zebra", "snake", "elephant", "koala", "hat", "cow", "penguin",
    "octopus", "leopard", "book", "jacket", "cheese", "car", "banana", "cat", "lemon",
    "zeppelin", "orange", "butterfly", "piano", "duck", "ball", "umbrella", "dog", "moon",
    "zebra", "snake", "elephant", "koala", "hat", "cow", "penguin", "octopus", "leopard",
    "book", "jacket", "cheese", "car", "banana", "cat", "lemon", "zeppelin", "orange",
    "butterfly", "piano", "duck", "ball", "umbrella", "dog", "moon", "zebra", "snake",
    "elephant", "koala", "hat", "cow", "penguin", "octopus", "leopard", "book", "jacket",
    "cheese", "car", "banana", "cat", "lemon", "zeppelin", "orange", "butterfly", "piano",
    "duck", "ball", "umbrella", "dog", "moon", "zebra", "snake", "elephant", "koala",
    "hat", "cow", "penguin", "octopus", "leopard", "book", "jacket", "cheese", "car",
    "banana", "cat", "lemon", "zeppelin", "orange", "butterfly", "piano", "duck", "ball",
    "umbrella", "dog", "moon", "zebra", "snake", "elephant", "koala", "hat", "cow",
    "penguin", "octopus", "leopard", "book", "jacket", "cheese", "car", "banana", "cat",
    "lemon", "zeppelin", "orange", "butterfly", "piano", "duck", "ball", "umbrella", "dog",
    "moon", "zebra", "snake", "elephant", "koala", "hat", "cow", "penguin", "octopus",
    "leopard", "book", "jacket", "cheese", "car", "banana", "cat", "lemon", "zeppelin",
    "orange", "butterfly", "piano", "duck", "ball", "umbrella", "dog", "moon", "zebra",
    "snake", "elephant", "koala", "hat", "cow", "penguin", "octopus", "leopard", "book",
    "jacket", "cheese", "car", "banana", "cat", "lemon", "zeppelin", "orange", "butterfly",
    "piano", "duck", "ball", "umbrella", "dog", "moon", "zebra", "snake", "elephant",
    "koala", "hat", "cow", "penguin", "octopus", "leopard", "book", "jacket", "cheese",
    "car", "banana", "cat", "lemon", "zeppelin", "orange", "butterfly", "piano", "duck",
    "ball", "umbrella", "dog", "moon", "zebra", "snake", "elephant", "koala", "hat",
    "cow", "penguin", "octopus", "leopard", "book", "jacket", "cheese", "car", "banana",
    "cat", "lemon", "zeppelin", "orange", "butterfly", "piano", "duck", "ball", "umbrella",
    "dog", "moon", "zebra", "snake", "elephant", "koala", "hat", "cow", "penguin",
    "octopus", "leopard", "book", "jacket", "cheese", "car", "banana", "cat", "lemon",
    "zeppelin", "orange", "butterfly", "piano", "duck", "ball", "umbrella", "dog", "moon",
    "zebra", "snake", "elephant", "koala", "hat", "cow", "penguin", "octopus", "leopard",
    "book", "jacket", "cheese", "car", "banana", "cat"};

    public twstrings() {
    
        
    
    }

    public String getWords(int i) {
        return words[i];
    }

//    public void setWords(String[] words) {
//        this.words = words;
//    }
    
    
    
    

    
    
}
